version: 0.2-{build}
skip_tags: true
build_script:
- cmd: >-
    appveyor.bat
on_failure:
- 7z a -mx9 -r fail.7z *.exe *.sln *.txt *.log
- appveyor.exe PushArtifact fail.7z
test: off
artifacts:
- path: qbittorrent-portable.7z
- path: 32bit_iphlpapi.dll
- path: 64bit_iphlpapi.dll
skip_commits:
  files:
    - 'LICENSE'
    - '*.md'
    - '.gitingore'
    - '.gitattributes'